In [1]:
## initially Lets import numpy

import numpy as np

In [2]:
my_lst=[1,2,3,4,5]

arr=np.array(my_lst)
print(arr)

[1 2 3 4 5]


In [3]:
type(arr)

numpy.ndarray

In [13]:
## Multinested array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr1=np.array([my_lst1,my_lst2,my_lst3])

In [14]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [15]:
type(arr1)
## check the shape of the array

arr1.shape

(3, 5)

Indexing 

In [16]:
## Accessing the array elements

arr

array([1, 2, 3, 4, 5])

In [17]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [18]:
arr1[1:,:2]

array([[2, 3],
       [9, 7]])

In [19]:
arr1[:,3:]

array([[4, 5],
       [5, 6],
       [8, 9]])

In [22]:
arr[3:]=100

In [24]:
arr

array([  1,   2,   3, 100, 100])

In [25]:
val=2

arr[arr<3]

array([1, 2])

In [26]:
## Create arrays and reshape

np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [27]:
arr1=np.arange(0,10).reshape(2,5)

In [28]:
arr2=np.arange(0,10).reshape(2,5)

In [29]:
arr1*arr2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [31]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [32]:
## random distribution
np.random.rand(3,3)

array([[0.21710049, 0.82734192, 0.82255103],
       [0.16173261, 0.46160665, 0.84163787],
       [0.33238332, 0.35917446, 0.34649523]])

In [33]:
arr_ex=np.random.randn(4,4)

In [34]:
arr_ex

array([[-0.73101914,  0.99540376, -1.64449942,  0.40771172],
       [-0.32702442,  0.09166752, -0.96483658, -0.23132776],
       [-0.39070888, -0.54303093, -0.84966022,  1.3428264 ],
       [-0.7322816 ,  1.40521707, -0.20063842, -0.42472461]])

In [37]:
np.random.randint(0,100,8).reshape(4,2)

array([[49, 72],
       [92, 90],
       [66, 44],
       [ 7,  8]])

In [38]:
np.random.random_sample((1,5))

array([[0.66812877, 0.03330274, 0.99128406, 0.19613424, 0.65629758]])